version: '3.8'
services:
  # fe-app:
  #   image: fe-container:first
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - nest-app
  #   restart: always
  #   networks:
  #     - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
    env_file:
      - .env
  mysql-container:
    image: mysql
    volumes:
      - /Users/seven/studyRepos/meeting_room_booking_system/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: seven
    ports:
      - 3306:3306
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/seven/studyRepos/meeting_room_booking_system/redis:/data
    ports:
      - 6379:6379
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
